### ISSUE TITLE
High CPU usage in 10.0.0-nas8

### ISSUE THREAD

**Issue by gourdo1** [dianlight/hassio-addons#134]
Ever since updating from 10.0.0-nas7 to 10.0.0-nas8, I have been experiencing high CPU usage from this add-on. **Note that MQTT is disabled**. I'm able to access my share no problem, but CPU usage is noticeably high, showing anywhere from 11 to over 20% usage while completely idle.

Below is my log shortly after starting:
[log.txt](https://github.com/dianlight/hassio-addons/files/10714595/log.txt)

Nothing obvious in there that I hadn't seen before, so not sure what it could be.

Running HAOS 2023.2.3 with everything else up-to-date.

For context, here's a view of my HAOS Raspberry Pi CPU temp and usage, showing when SambaNAS addon was updated to nas8, and Add-on CPU usage starting near the end in purple...
<img width="1561" alt="Screenshot 2023-02-11 121008" src="https://user-images.githubusercontent.com/13145881/218279198-b743a5af-6f0c-43a6-8dad-dd72c4f519f8.png">

**Comment by dianlight** [comment]
I found a bug in the script that call unnecessary smartctl. But the effect while be about a supplement of 4% of CPU usage in idle not about 20% as you report.  
I need the startup addon log and your addon configuration. Also i you describe your environment is usefull.

In the last, have you try to reboot the host ( a complete reboot )? sometime after ad addon-upgrade the docker engine don't release all cpu triggers.

L.

**Comment by gourdo1** [comment]
I restored a backup to NAS7 last night, and just re-upgraded to NAS8 to obtain some usage history. I will hardware reboot the host now and capture more history for the next few hours to see what happens to the CPU.

I'm running HAOS (2023.2.3 with everything up-to-date) on a RPi 4 8GB with HAOS installed on a USB3-connected SSD and a second USB3-connected 4TB Sandisk SSD as the Samba-connected media drive. A dual USB enclosure connects both drives and is powered by a separate 3A power supply.

Not sure what you mean by startup addon log... Here's the full log from Settings-->System-->Logs-->SambaNAS
[1a32f091_sambanas_2023-02-12T19-20-32.549Z.log](https://github.com/dianlight/hassio-addons/files/10717003/1a32f091_sambanas_2023-02-12T19-20-32.549Z.log)

Here's Supervisor Log if that's helpful:
[supervisor_2023-02-12T19-24-15.178Z.log](https://github.com/dianlight/hassio-addons/files/10717007/supervisor_2023-02-12T19-24-15.178Z.log)

Here's my SambaNAS config:

workgroup: WORKGROUP
username: me
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
automount: true
moredisks:
  - SandiskUltra4TB
available_disks_log: false
medialibrary:
  enable: false
  ssh_private_key: <YOU SUPER SECRET PRIVATE KEY>
veto_files: []
compatibility_mode: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: xxxxxxxx
log_level: notice

**Comment by gourdo1** [comment]
So here's the story so far today. I restored a backup around midnight last night to go back to 10.0.0-nas7. You can see that the CPU alternates between periods of zero and about 8% usage all night long. This seems high and rather strange on its own, given that there was no disk access or usage whatsoever during this period. By comparison, my NodeRed add-on which has over 1100 nodes and dozens of flows stays mostly around 0-2%, with rare peaks up to around 6%.

With 10.0.0-nas8, things are clearly worse. Right after upgrading to it at 11am today, my CPU spiked to 25% and continues to spike up and down much higher than nas7, even after I hardware rebooted the system 45 minutes later...

<img width="1103" alt="Screenshot 2023-02-12 131055" src="https://user-images.githubusercontent.com/13145881/218337566-a0ad303e-5356-4d94-9b9d-368ccdead1d1.png">

**Comment by gourdo1** [comment]
Restarted add-on with log level set to notice and mqtt_use_legacy_entities set to true. Not sure why either would have much of an impact, as MQTT is off, and logs are sparse, but seems at least one of the settings helped:

<img width="1543" alt="Screenshot 2023-02-12 163805" src="https://user-images.githubusercontent.com/13145881/218347214-0cc3da2f-b621-4958-98eb-67f46a348ffa.png">

So now I'm wondering whether the underlying MQTT module is still running in the background doing a lot of silent logging and hogging of the CPU, even though it's disabled and unconfigured...

**Comment by dianlight** [comment]
As I see also with legacy MQTT integration the load of cpu is abnormal. 
Your config is quite standard I try to replicate. 

Meanwhile you ca try:

In the log I see you have wlan0 up but without ip. 
- force the interface to eth0 ( interface option )

The main difference between nas7 and nas8 is the smartd daemon.
- disable smart ( enable_smart option ). If you can send me the content of sambanas MQTT topic is also useful.

The legacy MQTT is better so I suppose the problem I was right to search in the disk status query. For test, and as workaround if you don't need disk sensors 
- disable mqtt integration totally ( mqtt_enable option )

Regards
L

**Comment by gourdo1** [comment]
Can you explain how to force the interface to eth0 in HAOS? Where would I do this? I already see wlan0 has both IPv4 and IPv6 disabled.

That's weird that the MQTT option being switched off in the config UI doesn't actually show up in the YAML configuration. Instead, I have to turn the option on first, then switch to YAML editing, and set the optino to false explicitly. This seems counterintuitive.

Anyway, I explicitly turned both mqtt and smart off in the YAML now... Will see what happens to CPU use over night.

**Comment by gourdo1** [comment]
Those changes fixed it. Down to zero CPU usage now.  RPi also dropped nearly 6 degrees C over that time. This really needs to be the default state of the addon unless someone explicitly needs MQTT. Not sure if Smart is contributing any, but either way, this is too big a hit for logging messages.

<img width="1102" alt="Screenshot 2023-02-13 034605" src="https://user-images.githubusercontent.com/13145881/218449691-58690950-32dc-4fff-9deb-c489594111c9.png">

**Comment by dwitkows00** [comment]
Hi people,  to help you I have the same issue happening here, if I enable mqtt integration, CPU increase to about 50% and CPU temp increased about 6 or 7 degrees...
I set interface to eth0 and disabled smart, but the issue is happening when mqtt integration is set to on.

Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend: 20230202.0 - latest
RPI 4 / 4GB ram

**Comment by dianlight** [comment]
I did my homework and finally found and replicated the problem. It is not a CPU consumption problem but an IO one; unfortunately in a docker vm one leads to the other.
MQTT integration to bring information to HA requires 3 different steps; read, transform, send. The reading is done through iostats and smartctl but on these controllers I generate a blocking io request which generates wait peaks that you see as cpu. The transformation is done in pipe with the reading, being the reading also blocking the transformation process of the waiting cpu kind and finally the sending which, being done via socket (MQTT) also generates io which is added to the rest.

As a solution I'm preparing a version that uses asynchronous pipes for communication between the 3 steps (reading, transforming, sending). From the first tests it allows even with one of these controllers to have an average load of 6% against 15% of the current version. But this is still not sufficient also because it is multiplied by the number of disks therefore if there are 2 disks we speak of 12%, 3 18% ...

For now, the correct solution for those who have this type of problem is to give up MQTT integration or go back to the "legacy" one that reports disk space only. In any case I'm working to optimize everything and maybe create an autodetect for these types of controllers and disable the reading of statistics if found.

**Comment by gourdo1** [comment]
@dianlight This is good to hear. I think most home users would simply like to see a percentage disk utilized that updates a few times a day. If that requires MQTT, I guess that's fine, but I personally wouldn't enable it if it eats up any ongoing CPU resources. For this reason, I would still recommend MQTT be default disabled, as I expect most home users are not very likely to need such close monitoring of what is usually a media sharing drive.
