### ISSUE TITLE
🐛 [Sambanas] bug with "double" files due to mounting, using frigate

### ISSUE THREAD

**Issue by borgqueenx** [dianlight/hassio-addons#200]
### Addon

SambaNAS

### Description

When using frigate add-on & integrations on HAOS, as soon as i use sambanas and add the nas as media drive in haos settings -> network storage, frigate picks up the drive correctly and starts using it. however, even on a freshly formatted drive, on the frigate storage tab it says it used already more then 220gb+ (it just started on this fresh formatted drive). it also calculated the space in used double, as files are present on both /frigate and /media/frigate. deleting a file from either location also deletes it in the other, so the files are not double, but frigate does calculate it as double. so something is off with the mounting process it would seem.
the drive is labelled frigate and i automount it with sambanas under that name. the only other setting i played with is the media library to true and false. when i change it to false and restart, i can still see the media folder when browsing on the drive using windows.

### Reproduction steps

```bash
using HAOS and frigate full-access add-on.
format a drive to ext4, label it frigate.
install sambanas and mount the drive to usb on the pc, using the frigate label.
select it as media drive with the name frigate in network drives in home assistant settings with the user and pass you made.
start frigate and go to the storage tab and watch how it already used some space apparantly, and watch how it uses a lot more storage space then it did in the past.
```

### Addon Logs

```bash
currently cant help with this, i have mounted the drive on usb using udev rules i created:
https://community.home-assistant.io/t/solved-mount-usb-drive-in-hassio-to-be-used-on-the-media-folder-with-udev-customization/258406/135
And I can't figure out a way to undo this.
(it worked fine but the telegram bot cannot attach videos anymore using this udev rules)
```

### Addon Config

```bash
same as above.
```

### Architecture

aarch64

### OS

HaOS

**Comment by dianlight** [comment]
@borgqueenx  I made some test with Frigate addon. 
From what I understand you are mounting the same disk on both the medialibrary and frigate sides. You have two possibilities:
- Use SambaNas  `medialibrary` functionality and don't  mount the disk on the Frigate addon. You already see it inside /media. You also see the content of the disk in HA.
- Use Frigrate's functionality to mount network disks, disable the `medialibrary` option on sambanas and let Frigrate do everything. You can only see the content of the disk outside the HA environment mounting the cifs disk from a PC/MAC.

L.

**Comment by borgqueenx** [comment]
i played around and cannot get it working.
with medialibrary disabled on sambanas addon, and mounting the network drive in haos settings, it first gives a error that the folder is not empty. clicking the config window away shows it was mounted anyway. however frigate add-on>storage shows it still uses the internal 1tb drive.
With medialibrary enabled (and a reboot) i notice that it tried to automatically mount it in settings>network drive, but used a weird non-local ip address and failed. frigate again also still uses the internal drive.

perhaps it's possible to make this add-on work specifically for frigate with a toggle "use for frigate" to make it easier?

And from your comment, in both your options you mention "frigate's functionality to mount network disks". i think you mean home assistant here? as far as i know, frigate does not do this.

**Comment by dianlight** [comment]
Given that I don't use frigate and I don't have an environment to install the addon to test. 

- To use network share with frigate in a hassos environment you need to mount the network share as media with the name of frigate ( note the lower case ). See issue #201

- Sambanas is a generic mount and share system that follows the cifs specifications so the shares are exposed all uppercase. Use mixed case generate incompatibility and permission problems with Windows pc because is case-preserved not case-insensitive.

As other user you need to disable 'mediafolder' support so the disk is mounted in /mnt/<LABELNAME> and then follow the mount sequence for smb share in hassos to put in the /media/frigate ( all lowercase ) disk and use it. 
Any other sequence produces no mount ( empty folders ) or double mount.

I cannot add an options for frigate because any other solution or automatic system can be done only on the frigate addon side.

I suggest you to ask support on the frigate side.

L.
