### ISSUE TITLE
❓ [addon] Frigate mounting external drive all caps

### ISSUE THREAD

**Issue by lovelyjubley** [dianlight/hassio-addons#201]
### Addon

SambaNAS

### Your request

Firstly, thanks very much for this plugin, I have been using it for a while and have only just seen that you can use it to mount an external drive into Frigate which is great.
I can confirm the plugin works correctly and I can use smb to see the HA mounts and the newly mounted 'FRIGATE'
The issue is using this plugin mounts the system in caps, so what should be 'frigate' becomes 'FRIGATE' so Frigate ignores the mount and just creates its own 'frigate' mount again.

Am I completely missing something here or is there a workaround for this?

Thanks.

**Comment by dianlight** [comment]
The share are uppercase because cifs is case-preserving not case-sensitive so `FRIGATE` `Frigate` or `FriGate` are the sama share.  I don't understand why you need to mount again in Frigate Addon and this `mount` what really do.
I need to see myself the addon. Can you post the link of the Frigate addon?

**Comment by dianlight** [comment]
Can be a duplicate of #200

**Comment by dianlight** [comment]
The source of the problem is not the case of the share but the `automount` feature of the addon that use the share name as destination name for /media folder.  

I suggest you to change the frigate addon default config to point to the uppercase /media/FRIGATE folder to solve ( ref https://docs.frigate.video/frigate/installation ) or manually umount and remount the network disk and disable the `medialibrary` option in the SambaNas addon ( rif. https://docs.frigate.video/guides/ha_network_storage )

L.

**Comment by lovelyjubley** [comment]
Your second option worked. 
Thanks, your a legend 🙏
