### ISSUE TITLE
Feature Request - Spindown Idle HD

### ISSUE THREAD

**Issue by biochemguy** [dianlight/hassio-addons#34]
Hi, 

Like the title states, I would love to be able to spin down my NAS hard drive after being idle for a preset time (30 minutes or 1 hour), as I probably access it only a few hours per day. 

This would reduce noise and wear on the hard drive. 

Thanks for the great add-on and keep up the good work!

**Comment by lullerboi** [comment]
I'd love this, too.
There are external cases which do this properly on their own - not like the one I'd like to use (Icy Box IB-RD3621U3).

For this case, I had to use "sudo hd-idle -t /dev/disk/by-label/RAID" to spin it down (mostly because of the fan, I use SSDs).
So it would be awesome if you would implement it with this command as a service and a configurable setting (per drive?) for the timer. Might be the best option to reliably spin-down older drive models as well.

**Comment by dianlight** [comment]
Released in nas8
