### ISSUE TITLE
Samba add-on  doesn’t detect the Zerotier card

### ISSUE THREAD

**Issue by ciechomir** [dianlight/hassio-addons#80]
I have the following problem. 
I’m using the Zerotier network, the official Samba add-on (yours too;) uses the default NIC, doesn’t detect the Zerotier card.
Could you please add the option to use other network cards as in addition:

https://github.com/lmagyar/homeassistant-addon-samba-interface

README.md
https://github.com/lmagyar/homeassistant-addon-samba-interface/tree/master/samba

This option is:
**interfaces: [ ]**

**Comment by dianlight** [comment]
I've done some testing and I don't think adding the parameter in your case will fix it. 
My samba addon  by default is exposed on all interfaces, with the parameter you would limit only the perimeter.

I would ask you to confirm that the addon in the "Imagyr" version works in your case and send me the starting  log so that I can understand what the real difference.

L.

**Comment by dianlight** [comment]
Also try the new 9.7.0-NAS version and check in the log if in the row `INFO: Interfaces: ` there are also the zerotier.

L.

**Comment by ciechomir** [comment]
[text_file.txt](https://github.com/dianlight/hassio-addons/files/8940289/text_file.txt)

**Comment by dianlight** [comment]
Relesed in 9.7.0-nas1

**Comment by ciechomir** [comment]
When are you planning to release a new version? 
Thank you in advance :)
