### ISSUE TITLE
How to mount Drive

### ISSUE THREAD

**Issue by jsantosdias** [dianlight/hassio-addons#88]
Hello!
I am a rookie in these matters, but I have a USB disk in my router and I would like plex to read from that disk. I have Samba access to it and it works great with Windows. I need HASS to have access to that disk. How can I mount that drive so that Plex can use it as content?

Thank you!
João Dias

**Comment by dianlight** [comment]
There are some solutions but this is not the right place for a discussion. I suggest you to join to the community. 

https://community.home-assistant.io/latest

**Comment by jsantosdias** [comment]
I used PLEX with NAS. It's deprecated. I uninstalled it. It said I could used this add-on to replace it. How can I use it to access the router disk?

**Comment by dianlight** [comment]
It is deprecated because I don't maintain it anymore. It was initially created to mount smb in loopback from sambanas addon and because now external disk are mounted in /media I don't need it anymore. I have no time to maintain addons that I don't use. 

You can continue to use but I suggest to use another way. 
For example you can install Plex on your Router ( if is supported) or connect the usb disc to ha ( use sambanas addon ). 
I don't know your solution so I can't suggest you right solution.
Also feel free to fork my repository ad maintain yourself the addon. 

L.

**Comment by jsantosdias** [comment]
Thank you very much! I will try that!
